# Generated by Django 5.1.6 on 2025-02-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "SendMailService",
            "0002_alter_mailing_options_alter_message_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Запущена", "Запущена"),
                    ("Завершена", "Завершена"),
                    ("Отключена", "Отключена"),
                ],
                default="Создана",
                max_length=9,
                verbose_name="Статус",
            ),
        ),
    ]
